minor

diff --git a/code/main b/code/main
--- a/code/main
+++ b/code/main
@@ -11,21 +11,21 @@ fi
 if [[ "$1" = "copy" ]]; then
   if [[ "$2" = "all" ]]; then
     echo "Copying batch files to:"
-	cp -vi "${STANDALONE}"/*.m "$3"
-	exit 0
+	  cp -vi "${STANDALONE}"/*.m "$3"
+	  exit 0
   elif [[ -f "${STANDALONE}"/"$2" ]]; then
-	echo "Copying batch file to:"    
-	cp -vi "${STANDALONE}"/"$2" "$3"
-	exit 0
+	  echo "Copying batch file to:"    
+	  cp -vi "${STANDALONE}"/"$2" "$3"
+	  exit 0
   else
-	echo "ERROR: batch file $2 not found. Available batch files are:"
-	find "${STANDALONE}" -name "*.m" -printf "%f\n"
-	exit 1
+	  echo "ERROR: batch file $2 not found. Available batch files are:"
+	  find "${STANDALONE}" -name "*.m" -printf "%f\n"
+	  exit 1
   fi
 elif [[ "$1" = "view" ]]; then
   if [[ -f "${STANDALONE}"/"$2" ]]; then
-	cat "${STANDALONE}"/"$2"
-	exit 0
+	  cat "${STANDALONE}"/"$2"
+	  exit 0
   else
     echo "ERROR: batch file $2 not found. Available batch files are:"
     find "${STANDALONE}" -name "*.m" -printf "%f\n"
